// <auto-generated />
using System;
using HHPW_BE;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HHPW_BE.Migrations
{
    [DbContext(typeof(HHPWDbContext))]
    [Migration("20240419012356_secondCreate")]
    partial class secondCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HHPW_BE.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Four Cheese",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Margarita",
                            Price = 9.49m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chicken Alfredo",
                            Price = 11.99m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Veggie Delight",
                            Price = 12.49m
                        });
                });

            modelBuilder.Entity("HHPW_BE.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .HasColumnType("text");

                    b.Property<string>("PaymentType")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Tip")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            Name = "Alice Brown",
                            OrderType = "Dine-in",
                            PaymentType = "Debit Card",
                            Phone = "111-222-3333",
                            Status = true,
                            Tip = 3m
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            Name = "Bob Green",
                            OrderType = "Pickup",
                            PaymentType = "Cash",
                            Phone = "444-555-6666",
                            Status = false,
                            Tip = 12m
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@example.com",
                            Name = "Charlie White",
                            OrderType = "Delivery",
                            PaymentType = "Online",
                            Phone = "777-888-9999",
                            Status = false,
                            Tip = 1.2m
                        },
                        new
                        {
                            Id = 4,
                            Email = "david@example.com",
                            Name = "David Black",
                            OrderType = "Dine-in",
                            PaymentType = "Credit Card",
                            Phone = "123-456-7890",
                            Status = true,
                            Tip = 4.4m
                        },
                        new
                        {
                            Id = 5,
                            Email = "eva@example.com",
                            Name = "Eva Red",
                            OrderType = "Pickup",
                            PaymentType = "Cash",
                            Phone = "987-654-3210",
                            Status = false,
                            Tip = 12m
                        },
                        new
                        {
                            Id = 6,
                            Email = "frank@example.com",
                            Name = "Frank Yellow",
                            OrderType = "Delivery",
                            PaymentType = "Online",
                            Phone = "456-789-0123",
                            Status = false,
                            Tip = 5.2m
                        });
                });

            modelBuilder.Entity("HHPW_BE.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HHPW_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Cashier")
                        .HasColumnType("boolean");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cashier = true,
                            Uid = "J4tmBKI4tGYLAcxcswvolIKzeFv2"
                        },
                        new
                        {
                            Id = 2,
                            Cashier = false,
                            Uid = "J4tmBKI4tGYLAcxc4wvolIKzeFv4"
                        });
                });

            modelBuilder.Entity("HHPW_BE.Models.OrderItem", b =>
                {
                    b.HasOne("HHPW_BE.Models.Item", "Item")
                        .WithMany("Orders")
                        .HasForeignKey("ItemId");

                    b.HasOne("HHPW_BE.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HHPW_BE.Models.Item", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HHPW_BE.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
